cache-dir = "./.ruff_cache"
fix = false
fix-only = false
indent-width = 4
line-length = 120
output-format = "full"
respect-gitignore = false
target-version = "py312"

[format]
docstring-code-format = true
docstring-code-line-length = 100
indent-style = "space"
line-ending = "native"
quote-style = "double"
skip-magic-trailing-comma = true
